### ISSUE TITLE
Unable to login on Linux without KWallet or GNOME Keyring

### ISSUE THREAD

**Issue by Spencer-0003** [Snd-R/Komelia#1]
Related: https://github.com/javakeyring/java-keyring/issues/96

Trying to login when using any other secret service integration (KeepassXC in my case) Komelia will just freeze with the following error:

```
21:44:16.602 [AWT-EventQueue-0] ERROR org.freedesktop.secret.handlers.SignalHandler -- Cloud not acquire a prompt.
org.freedesktop.secret.errors.NoSuchObject: /org/freedesktop/secrets/prompt/533434d666f14ae6b21a493ec8a7fcd5
	at org.freedesktop.secret.Prompt.prompt(Prompt.java:41)
	at org.freedesktop.secret.Prompt.lambda$await$0(Prompt.java:63)
	at org.freedesktop.secret.handlers.SignalHandler.await(SignalHandler.java:144)
	at org.freedesktop.secret.Prompt.await(Prompt.java:62)
	at org.freedesktop.secret.Prompt.await(Prompt.java:80)
	at com.github.javakeyring.internal.freedesktop.SimpleCollection.createItem(SimpleCollection.java:316)
	at com.github.javakeyring.internal.freedesktop.FreedesktopKeyringBackend.setPassword(FreedesktopKeyringBackend.java:124)
	at com.github.javakeyring.Keyring.setPassword(Keyring.java:107)
	at io.github.snd_r.komelia.settings.KeyringSecretsRepository.setCookie(KeyringSecretsRepository.kt:33)
	at io.github.snd_r.komelia.http.RememberMePersistingCookieStore.addCookie(RememberMePersistingCookieStore.kt:25)
	at io.ktor.client.plugins.cookies.HttpCookies.saveCookiesFrom$ktor_client_core(HttpCookies.kt:78)
	at io.ktor.client.plugins.cookies.HttpCookies$Companion$install$3.invokeSuspend(HttpCookies.kt:124)
	at io.ktor.client.plugins.cookies.HttpCookies$Companion$install$3.invoke(HttpCookies.kt)
	at io.ktor.client.plugins.cookies.HttpCookies$Companion$install$3.invoke(HttpCookies.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
	at io.ktor.client.plugins.DoubleReceivePluginKt$SaveBodyPlugin$2$1.invokeSuspend(DoubleReceivePlugin.kt:72)
	at io.ktor.client.plugins.DoubleReceivePluginKt$SaveBodyPlugin$2$1.invoke(DoubleReceivePlugin.kt)
	at io.ktor.client.plugins.DoubleReceivePluginKt$SaveBodyPlugin$2$1.invoke(DoubleReceivePlugin.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:74)
	at io.ktor.client.HttpClient$2.invokeSuspend(HttpClient.kt:145)
	at io.ktor.client.HttpClient$2.invoke(HttpClient.kt)
	at io.ktor.client.HttpClient$2.invoke(HttpClient.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
	at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(HttpClientEngine.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:62)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2$1.invoke(FlushCoroutineDispatcher.skiko.kt:57)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.performRun(FlushCoroutineDispatcher.skiko.kt:99)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher.access$performRun(FlushCoroutineDispatcher.skiko.kt:37)
	at androidx.compose.ui.platform.FlushCoroutineDispatcher$dispatch$2.invokeSuspend(FlushCoroutineDispatcher.skiko.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Snd-R** [comment]
Should be fixed in the latest secret service dependency
https://github.com/swiesend/secret-service/commit/1717f51eeae68dde4baa9bb1e743c2682e06f09a

**Comment by Snd-R** [comment]
Not sure how it was working for you but updated dependency had incompatible interface
I didn't catch it since I was using kwallet which still would've worked.
Should be fixed with explicit implementation that uses new version
