### ISSUE TITLE
android apk java error

### ISSUE THREAD

**Issue by Cissoubaka** [Snd-R/Komelia#11]
I had tried to install 0.10.1 on my fire HD 8 (10th gen) with FireOS 7.3.1.5
but that drops me this error :

`java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /system/framework/core-oj.jar)
    at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypesForUrl(DatabaseTypeRegister.java:58)
    at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:116)
    at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:96)
    at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1547)
    at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:635)
    at snd.komelia.db.DatabaseKt.flywayMigrate(Database.kt:33)
    at snd.komelia.db.DatabaseKt.access$flywayMigrate(Database.kt:1)
    at snd.komelia.db.Database.<init>(Database.kt:18)
    at snd.komelia.AndroidDependencyContainer$Companion.createInstance(AndroidDependencyContainer.kt:101)
    at snd.komelia.MainActivity$onCreate$1.invokeSuspend(MainActivity.kt:50)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
    Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ad0136f, Dispatchers.Default]`

every working fine if using version 0.9.0

**Comment by redfieldw** [comment]
I have the same issue, I'm with Android OS 15.
